#!/bin/bash
# 
sudo losetup /dev/loop0 ./sdcard.img
sudo kpartx -a /dev/loop0
sudo mount /dev/mapper/loop0p1 /media/bootfs

for var
do
   sudo cp $var /media/bootfs
done
sync;sync;sync
sudo umount /media/bootfs
sudo kpartx -d /dev/loop0
sudo losetup -d /dev/loop0
